cooldown: 5
badwords:
  - godverdomme
  - gvd
  - fuck
  - kut
  - teringlijer
  - tering
  - tieves
  - tyfus
  - tefus
  - kanker
  - kk
  - kkr
  - nazi
  - nazie
  - k*nker
  - f*ck
  - kutkind
  - gay
  - homo